window.KG_CONFIG = {
  langKey: "comp9123_lang",
  fromParam: "kg",
  numChapters: 10,
  chapterColors: {
    1: "#f59e0b", 2: "#ea580c", 3: "#d97706", 4: "#84cc16", 5: "#16a34a",
    6: "#059669", 7: "#0d9488", 8: "#0891b2", 9: "#2563eb", 10: "#7c3aed",
  },
  chapterNames: {
    1: "W1: Intro & analysis", 2: "W2: Lists", 3: "W3: Stacks/queues/lists", 4: "W4: Trees",
    5: "W5: BST/AVL", 6: "W6: Maps/heaps", 7: "W7: Hashing", 8: "W8: Graphs",
    9: "W9: Graph algorithms", 10: "W10: Greedy",
  },
  chapterNamesZh: {
    1: "第1周", 2: "第2周", 3: "第3周", 4: "第4周", 5: "第5周",
    6: "第6周", 7: "第7周", 8: "第8周", 9: "第9周", 10: "第10周",
  },
  ui: {
    en: {
      title: "Knowledge Graph — COMP9123", navHome: "← Home", navMath: "", pageTitle: "Knowledge Graph",
      search: "Search concepts...", threshold: "Threshold", diff: "Sort by Difficulty", chapter: "Group by Chapter", reset: "Reset View",
      weeks: "Weeks",
      w1: "W1 Intro", w2: "W2 Lists", w3: "W3 Stacks/queues", w4: "W4 Trees", w5: "W5 BST/AVL",
      w6: "W6 Heaps", w7: "W7 Hash", w8: "W8 Graphs", w9: "W9 Algos", w10: "W10 Greedy",
      legendDiff: "Difficulty", diffScale: "● small = easy", click: "Click node → source",
      layout: "Layout", sort: "Sort by difficulty", group: "Group by chapter",
      both: "Combine filters.", nodes: "nodes", edges: "edges", thresholdStats: "threshold ≥ ",
    },
    zh: {
      title: "知识图谱 — COMP9123", navHome: "← 首页", navMath: "", pageTitle: "知识图谱",
      search: "搜索…", threshold: "阈值", diff: "按难度", chapter: "按章节", reset: "重置",
      weeks: "周次",
      w1: "W1", w2: "W2", w3: "W3", w4: "W4", w5: "W5", w6: "W6", w7: "W7", w8: "W8", w9: "W9", w10: "W10",
      legendDiff: "难度", diffScale: "● 小=易", click: "点击跳转",
      layout: "布局", sort: "难度排序", group: "章节分组",
      both: "组合筛选", nodes: "节点", edges: "边", thresholdStats: "阈值 ≥ ",
    },
  },
  nodes: [
    ["w1-o", 1, 1, "Big-O", "Upper bound on asymptotic growth; Ω and Θ for lower and tight bounds.", "../chapters/chapter1/web/chapter1-study.html#sec-complexity"],
    ["w1-adt", 1, 1, "Goals & abstractions", "Computational problem, algorithm, and correctness/complexity analysis.", "../chapters/chapter1/web/chapter1-study.html#sec-goals"],
    ["w1-sum", 1, 2, "Σ & series", "Closed forms for ∑i, ∑i², ∑i³; Tutorial 1 warm-ups.", "../chapters/chapter1/web/chapter1-math.html#sec-m-summation"],
    ["w1-proof", 1, 3, "Discrete toolkit", "Logs, floors/ceilings, proof patterns, sets, probability (Tutorial 1).", "../chapters/chapter1/web/chapter1-math.html#sec-m-discrete"],
    ["w1-rec", 1, 2, "Recurrences & loops", "Divide-and-conquer intuition; nested loops to Θ(n²).", "../chapters/chapter1/web/chapter1-math.html#sec-m-asymptotic"],
    ["w2-arr", 2, 1, "Array-backed list", "Indexed access is O(1); middle inserts and deletes pay shifting costs.", "../chapters/chapter2/web/chapter2-study.html#sec-arrays"],
    ["w2-sum", 2, 2, "Summations", "Triangular numbers and geometric series.", "../chapters/chapter2/web/chapter2-math.html#sec-m-series"],
    ["w3-stack", 3, 1, "Stack LIFO", "Push, pop, top; recursion and delimiter matching.", "../chapters/chapter3/web/chapter3-study.html#sec-stack"],
    ["w3-queue", 3, 1, "Queue FIFO", "Enqueue/dequeue order for scheduling, buffering, and BFS-style processing.", "../chapters/chapter3/web/chapter3-study.html#sec-queue"],
    ["w3-dll", 3, 2, "Stack applications", "Method stacks and balanced-parentheses checking show why LIFO fits nested structure.", "../chapters/chapter3/web/chapter3-study.html#sec-method-stack"],
    ["w4-height", 4, 2, "Tree height", "Height looks downward to the deepest leaf and is often computed recursively from children.", "../chapters/chapter4/web/chapter4-study.html#sec-recursion"],
    ["w4-traverse", 4, 1, "Traversals", "Preorder, postorder, inorder, and Euler-tour timing on trees.", "../chapters/chapter4/web/chapter4-study.html#sec-traversal"],
    ["w4-bst", 4, 2, "Inorder traversal", "Left-node-right order on binary trees; it becomes sorted once BST ordering is added next week.", "../chapters/chapter4/web/chapter4-study.html#sec-inorder"],
    ["w5-avl", 5, 3, "AVL rotations", "Restore balance factor in {-1,0,1}.", "../chapters/chapter5/web/chapter5-study.html#sec-avl"],
    ["w5-bst", 5, 2, "BST path", "Search follows left/right by key.", "../chapters/chapter5/web/chapter5-study.html#sec-bst"],
    ["w6-heap", 6, 2, "Binary heap", "Array-stored complete tree.", "../chapters/chapter6/web/chapter6-study.html#sec-heap"],
    ["w6-pq", 6, 2, "Priority queue", "Insert / extract-min.", "../chapters/chapter6/web/chapter6-study.html#sec-pq"],
    ["w6-map", 6, 1, "Map ADT", "Key–value abstraction.", "../chapters/chapter6/web/chapter6-study.html#sec-map"],
    ["w7-hash", 7, 2, "Hash functions", "Map keys to slots.", "../chapters/chapter7/web/chapter7-study.html#sec-hash"],
    ["w7-chain", 7, 2, "Chaining", "Buckets of colliding keys.", "../chapters/chapter7/web/chapter7-study.html#sec-chain"],
    ["w7-open", 7, 3, "Open addressing", "Probe sequences; tombstones.", "../chapters/chapter7/web/chapter7-study.html#sec-open"],
    ["w8-rep", 8, 1, "Graph representations", "Adjacency list vs matrix.", "../chapters/chapter8/web/chapter8-study.html#sec-rep"],
    ["w8-dfs", 8, 2, "DFS", "Stack/recursion, edge classes.", "../chapters/chapter8/web/chapter8-study.html#sec-dfs"],
    ["w8-bfs", 8, 2, "BFS", "Queue, unweighted shortest paths.", "../chapters/chapter8/web/chapter8-study.html#sec-bfs"],
    ["w9-dijk", 9, 3, "Dijkstra", "Single-source shortest paths with non-negative weights and a priority queue.", "../chapters/chapter9/web/chapter9-study.html#sec-dijkstra"],
    ["w9-prim", 9, 3, "Prim", "Grow an MST by repeatedly taking the cheapest edge into the current tree.", "../chapters/chapter9/web/chapter9-study.html#sec-prim"],
    ["w9-krus", 9, 3, "Kruskal", "Sort edges by weight and use Union-Find to skip cycle-creating edges.", "../chapters/chapter9/web/chapter9-study.html#sec-kruskal"],
    ["w10-greedy", 10, 2, "Greedy template", "Local choice plus a correctness proof or counterexample.", "../chapters/chapter10/web/chapter10-study.html#sec-pattern"],
    ["w10-activity", 10, 2, "Scheduling", "Interval partitioning and objective-aware greedy ordering.", "../chapters/chapter10/web/chapter10-study.html#sec-scheduling"],
    ["w10-huff", 10, 3, "Huffman", "Merge the two lowest-frequency trees to build an optimal prefix code.", "../chapters/chapter10/web/chapter10-study.html#sec-huffman"],
  ].map(function (n) {
    return { id: n[0], ch: n[1], diff: n[2], label: n[3], def: n[4], href: n[5] };
  }),
  edges: [
    ["w1-adt", "w1-o", 8], ["w1-o", "w1-sum", 7], ["w1-sum", "w1-proof", 6], ["w1-proof", "w1-rec", 7], ["w1-o", "w1-rec", 7],
    ["w1-adt", "w2-arr", 6], ["w2-arr", "w3-stack", 5],
    ["w3-stack", "w3-queue", 8], ["w3-queue", "w8-bfs", 7], ["w3-stack", "w8-dfs", 7],
    ["w4-height", "w4-bst", 8], ["w4-bst", "w5-bst", 9], ["w5-bst", "w5-avl", 9],
    ["w6-heap", "w6-pq", 9], ["w6-map", "w7-hash", 7], ["w7-hash", "w7-chain", 8],
    ["w7-chain", "w7-open", 7], ["w8-rep", "w8-dfs", 8], ["w8-rep", "w8-bfs", 8],
    ["w8-bfs", "w9-dijk", 6], ["w9-dijk", "w9-prim", 7], ["w9-prim", "w9-krus", 6],
    ["w1-o", "w10-greedy", 4], ["w10-greedy", "w10-activity", 8], ["w10-greedy", "w10-huff", 7],
  ],
};
