window.KG_CONFIG = {
  langKey: "comp5046_lang",
  fromParam: "kg",
  numChapters: 6,
  chapterColors: { 1:"#6c8cff", 2:"#34d399", 3:"#fbbf24", 4:"#a78bfa", 5:"#f87171", 6:"#f472b6" },
  chapterNames: {
    1:"L1: Intro & NLP", 2:"L2: Text & n-grams", 3:"L3: Classify & LM",
    4:"L4: Embeddings", 5:"L5: Neural seq.", 6:"L6: Transformers"
  },
  chapterNamesZh: {
    1:"第1讲：绪论", 2:"第2讲：文本与 n-gram", 3:"第3讲：分类与 LM",
    4:"第4讲：词向量", 5:"第5讲：神经序列", 6:"第6讲：Transformer"
  },
  diffLabelsZh: ["","入门","中等","有挑战","进阶","专家"],
  nodes: [
    // ===== CHAPTER 1: Introduction & Representing Text =====
    { id:"n1-nlp",     ch:1, diff:1, label:"NLP definition",        def:"Algorithms mapping between human language and machine-usable representations.",            href:"../chapters/chapter1/web/chapter1-study.html#sec-overview" },
    { id:"n1-tasks",   ch:1, diff:1, label:"NLP task families",     def:"Tagging, classification, structured prediction (parsing), generation / transduction (MT, summarisation, dialogue).", href:"../chapters/chapter1/web/chapter1-study.html#sec-overview" },
    { id:"n1-wordnet", ch:1, diff:1, label:"WordNet",               def:"Lexical database with hypernym/hyponym/synonym-set relations; ~10^5 English nouns.",       href:"../chapters/chapter1/web/chapter1-study.html#sec-lexicons" },
    { id:"n1-onehot",  ch:1, diff:1, label:"One-hot vectors",       def:"Sparse vector with a single 1 at the word's index; synonyms are orthogonal (zero overlap).", href:"../chapters/chapter1/web/chapter1-study.html#sec-discrete" },
    { id:"n1-bow",     ch:1, diff:1, label:"Bag-of-words",          def:"Document = sum of one-hot counts; loses order but keeps frequency information.",            href:"../chapters/chapter1/web/chapter1-study.html#sec-discrete" },
    { id:"n1-tfidf",   ch:1, diff:2, label:"TF-IDF",                def:"Log-scaled term frequency × inverse document frequency; downweights corpus-wide common terms.", href:"../chapters/chapter1/web/chapter1-study.html#sec-tfidf" },
    { id:"n1-bm25",    ch:1, diff:2, label:"BM25",                  def:"IR scoring with TF saturation and document-length normalisation; parameters a, b.",         href:"../chapters/chapter1/web/chapter1-study.html#sec-tfidf" },
    { id:"n1-dist",    ch:1, diff:1, label:"Distributional hypothesis", def:"Words in similar contexts have similar meanings (Firth / Harris).",                     href:"../chapters/chapter1/web/chapter1-study.html#sec-distributional" },
    { id:"n1-svd",     ch:1, diff:2, label:"SVD for word vectors",  def:"Truncated SVD on co-occurrence matrix → dense distributional vectors (Schütze 1993).",       href:"../chapters/chapter1/web/chapter1-study.html#sec-distributional" },
    { id:"n1-cbow",    ch:1, diff:2, label:"CBOW",                  def:"Predict centre word from averaged context embeddings (Mikolov 2013).",                      href:"../chapters/chapter1/web/chapter1-study.html#sec-neural-preview" },
    { id:"n1-skip",    ch:1, diff:2, label:"Skip-gram",             def:"Predict context from centre word; often stronger than CBOW, especially for rare words.",    href:"../chapters/chapter1/web/chapter1-study.html#sec-neural-preview" },
    { id:"n1-window",  ch:1, diff:2, label:"Window size effect",    def:"Narrow window → syntactic similarity; wide window → semantic similarity.",                  href:"../chapters/chapter1/web/chapter1-study.html#sec-neural-preview" },
    { id:"n1-cosine",  ch:1, diff:2, label:"Cosine similarity",     def:"Direction-based similarity u·v / (‖u‖‖v‖); preferred over raw dot product for embeddings.", href:"../chapters/chapter1/web/chapter1-study.html#sec-eval-vectors" },
    { id:"n1-analogy", ch:1, diff:2, label:"Analogy test",          def:"v(w1)−v(w2)+v(w3) nearest-neighbour check (Paris−France+Italy ≈ Rome).",                   href:"../chapters/chapter1/web/chapter1-study.html#sec-eval-vectors" },
    { id:"n1-bias",    ch:1, diff:2, label:"Embedding bias",        def:"Pretrained embeddings can encode stereotypes; debiasing methods exist (Bolukbasi 2016).",   href:"../chapters/chapter1/web/chapter1-study.html#sec-eval-vectors" },
    { id:"n1-pipe",    ch:1, diff:1, label:"NLP pipeline",          def:"Collect → tokenise → represent → task model → decode; pretrained transformers may merge stages.", href:"../chapters/chapter1/web/chapter1-study.html#sec-pipeline" },
    { id:"n1-cooccur", ch:1, diff:2, label:"Co-occurrence matrix",  def:"Word–word count matrix from context windows; input to SVD and basis for distributional vectors.", href:"../chapters/chapter1/web/chapter1-study.html#sec-distributional" },
    { id:"n1-instab",  ch:1, diff:2, label:"Embedding instability", def:"Same data/model but different random seeds → different neighbours, especially rare words (WKM 2018).", href:"../chapters/chapter1/web/chapter1-study.html#sec-eval-vectors" },

    // ===== CHAPTER 2: Foundations of NLP Systems =====
    { id:"n2-five",    ch:2, diff:1, label:"Five components",       def:"Data, Model, Inference, Learning, Metric — the core architecture of any NLP system.",       href:"../chapters/chapter2/web/chapter2-study.html#sec-five" },
    { id:"n2-sent",    ch:2, diff:1, label:"Sentiment analysis",    def:"Binary pos/neg classification of movie reviews (Pang 2002); same template for spam, authorship.", href:"../chapters/chapter2/web/chapter2-study.html#sec-example" },
    { id:"n2-tok",     ch:2, diff:1, label:"Tokenisation & BoW",    def:"Whitespace split baseline; BoW count vector; stopwords; bigram / NOT_ negation features.",  href:"../chapters/chapter2/web/chapter2-study.html#sec-token-bow" },
    { id:"n2-linear",  ch:2, diff:2, label:"Linear classifier",     def:"Score = x·w + b; multi-class via argmax over weight vectors per class.",                    href:"../chapters/chapter2/web/chapter2-study.html#sec-linear" },
    { id:"n2-losses",  ch:2, diff:2, label:"Loss functions",        def:"0-1 (non-differentiable), hinge (margin), cross-entropy (smooth, standard for neural NLP).", href:"../chapters/chapter2/web/chapter2-study.html#sec-learn" },
    { id:"n2-percept", ch:2, diff:2, label:"Perceptron",            def:"Wrong prediction → add x to true-class weights, subtract from predicted-class; no learning rate.", href:"../chapters/chapter2/web/chapter2-study.html#sec-learn" },
    { id:"n2-logreg",  ch:2, diff:3, label:"Logistic gradient",     def:"∂L/∂w_j = (σ(x·w)−y)x_j — gradient of log loss for SGD updates.",                         href:"../chapters/chapter2/web/chapter2-study.html#sec-learn" },
    { id:"n2-embed",   ch:2, diff:2, label:"Embedding-based features", def:"Pool word embeddings (e.g. mean) as document vector; reuse GloVe; bias from pretraining.", href:"../chapters/chapter2/web/chapter2-study.html#sec-embed" },
    { id:"n2-split",   ch:2, diff:1, label:"Train / dev / test",    def:"Train fits, dev tunes (don't train final weights), test is rare — no daily peeking.",       href:"../chapters/chapter2/web/chapter2-study.html#sec-metrics" },
    { id:"n2-prf",     ch:2, diff:2, label:"Precision / Recall / F1", def:"P = TP/(TP+FP); R = TP/(TP+FN); F1 = harmonic mean; macro vs micro averaging.",          href:"../chapters/chapter2/web/chapter2-study.html#sec-metrics" },
    { id:"n2-roc",     ch:2, diff:2, label:"ROC / AUC",             def:"Sweep threshold → TPR vs FPR curve; AUC 0.5 = random, 1.0 = perfect; PR curve for rare positives.", href:"../chapters/chapter2/web/chapter2-study.html#sec-metrics" },
    { id:"n2-confmat", ch:2, diff:1, label:"Confusion matrix",     def:"TP/FP/FN/TN table crossing predicted vs true labels; foundation for P/R/F1.",                 href:"../chapters/chapter2/web/chapter2-study.html#sec-metrics" },
    { id:"n2-naiveB",  ch:2, diff:2, label:"Naive Bayes",          def:"Probability-based classifier with conditional independence assumption; fast BoW baseline.",     href:"../chapters/chapter2/web/chapter2-study.html#sec-learn" },
    { id:"n2-svm",     ch:2, diff:2, label:"SVM",                  def:"Maximum-margin linear classifier using hinge loss; strong text-classification baseline.",      href:"../chapters/chapter2/web/chapter2-study.html#sec-learn" },
    { id:"n2-ngrams",  ch:2, diff:1, label:"N-gram features",      def:"Consecutive n-word sequences as features; bigrams and NOT_-negation scope augment unigrams.",  href:"../chapters/chapter2/web/chapter2-study.html#sec-token-bow" },
    { id:"n2-stopw",   ch:2, diff:1, label:"Stopwords",            def:"High-frequency function words often removed in IR; sometimes crucial for authorship tasks.",   href:"../chapters/chapter2/web/chapter2-study.html#sec-token-bow" },
    { id:"n2-oov",     ch:2, diff:1, label:"OOV / unknown words",  def:"Test words not in training vocabulary; BoW drops them — motivates subword methods.",          href:"../chapters/chapter2/web/chapter2-study.html#sec-token-bow" },
    { id:"n2-imbal",   ch:2, diff:2, label:"Class imbalance",      def:"Skewed class distribution biases model to majority class; needs weighting/sampling/adjusted metrics.", href:"../chapters/chapter2/web/chapter2-study.html#sec-metrics" },

    // ===== CHAPTER 3: Non-linear Models =====
    { id:"n3-act",     ch:3, diff:1, label:"Activation functions",  def:"Sigmoid σ, tanh, ReLU max(0,x) — add non-linearity so networks can solve XOR-like problems.", href:"../chapters/chapter3/web/chapter3-study.html#sec-nl" },
    { id:"n3-mlp",     ch:3, diff:2, label:"MLP / feed-forward",    def:"Layer = affine + bias + activation; stacking layers → multi-layer perceptron.",             href:"../chapters/chapter3/web/chapter3-study.html#sec-nl" },
    { id:"n3-sgd",     ch:3, diff:2, label:"SGD",                   def:"Stochastic gradient descent on minibatches; noise helps escape local minima.",              href:"../chapters/chapter3/web/chapter3-study.html#sec-train" },
    { id:"n3-bp",      ch:3, diff:3, label:"Backpropagation",       def:"Chain rule on computation graph — forward cache values, backward propagate gradients.",     href:"../chapters/chapter3/web/chapter3-study.html#sec-train" },
    { id:"n3-reg",     ch:3, diff:2, label:"Regularisation",        def:"L1/L2 weight penalties; dropout (zero random units); early stopping on val loss.",          href:"../chapters/chapter3/web/chapter3-study.html#sec-reg" },
    { id:"n3-rnn",     ch:3, diff:2, label:"RNN / Elman cell",      def:"h_t = tanh(Wx_t + Vh_{t-1} + b); keeps hidden state per step to capture sequence order.",   href:"../chapters/chapter3/web/chapter3-study.html#sec-rnn" },
    { id:"n3-trenc",   ch:3, diff:2, label:"Transducer vs encoder", def:"Transducer: output per step (POS); encoder: one label from final h (sentiment).",           href:"../chapters/chapter3/web/chapter3-study.html#sec-rnn-use" },
    { id:"n3-bptt",    ch:3, diff:3, label:"BPTT",                  def:"Backprop through time — unroll RNN, sum gradient contributions from all steps.",            href:"../chapters/chapter3/web/chapter3-study.html#sec-rnn-use" },
    { id:"n3-vanexp",  ch:3, diff:2, label:"Vanishing / exploding gradients", def:"Repeated tanh + V multiplications shrink (vanish) or grow (explode) signals over time.", href:"../chapters/chapter3/web/chapter3-study.html#sec-grad-issues" },
    { id:"n3-clip",    ch:3, diff:2, label:"Gradient clipping",     def:"Cap gradient norm to prevent exploding; gated RNNs (LSTM/GRU) address vanishing.",         href:"../chapters/chapter3/web/chapter3-study.html#sec-grad-issues" },
    { id:"n3-lstm",    ch:3, diff:3, label:"LSTM",                 def:"Gated RNN with forget/input/output gates and cell state; additive path preserves long-range gradients.", href:"../chapters/chapter3/web/chapter3-study.html#sec-grad-issues" },
    { id:"n3-birnn",   ch:3, diff:2, label:"Bidirectional RNN",    def:"Two RNNs (left→right, right→left) whose hidden states are concatenated for full context.",   href:"../chapters/chapter3/web/chapter3-study.html#sec-rnn-use" },
    { id:"n3-pos",     ch:3, diff:1, label:"POS tagging",          def:"Assign a grammatical category (noun, verb, adj, …) to each token; classic sequence-labelling task.", href:"../chapters/chapter3/web/chapter3-study.html#sec-rnn-use" },
    { id:"n3-ner",     ch:3, diff:2, label:"Named Entity Recognition", def:"Identify and type named entities (person, location, org) in text; uses BIO tagging.",    href:"../chapters/chapter3/web/chapter3-study.html#sec-rnn-use" },
    { id:"n3-compg",   ch:3, diff:2, label:"Computation graph",    def:"DAG of operations enabling automatic differentiation; forward caches, backward propagates gradients.", href:"../chapters/chapter3/web/chapter3-study.html#sec-train" },
    { id:"n3-early",   ch:3, diff:1, label:"Early stopping",       def:"Stop training when validation loss plateaus; simple regularisation without changing the model.", href:"../chapters/chapter3/web/chapter3-study.html#sec-reg" },

    // ===== CHAPTER 4: Inference — Greedy & Search =====
    { id:"n4-mod",     ch:4, diff:1, label:"Model vs inference",    def:"Model scores (input,output) pairs; inference searches for the highest-scoring output.",     href:"../chapters/chapter4/web/chapter4-study.html#sec-blackbox" },
    { id:"n4-exh",     ch:4, diff:1, label:"Exhaustive search",     def:"Enumerate all candidates → argmax; exact but |T|^n is intractable for long sequences.",     href:"../chapters/chapter4/web/chapter4-study.html#sec-exhaustive" },
    { id:"n4-greedy",  ch:4, diff:1, label:"Greedy decoding",       def:"Best token one step at a time; O(n|T|) but may miss global optimum.",                      href:"../chapters/chapter4/web/chapter4-study.html#sec-greedy" },
    { id:"n4-topkp",   ch:4, diff:2, label:"Top-k / top-p sampling", def:"Top-k: fixed k highest tokens; top-p (nucleus): smallest set with cumulative prob ≥ p.",  href:"../chapters/chapter4/web/chapter4-study.html#sec-greedy" },
    { id:"n4-beam",    ch:4, diff:2, label:"Beam search",           def:"Keep top-K partial hypotheses; extend, score, prune; length-normalised scores.",            href:"../chapters/chapter4/web/chapter4-study.html#sec-beam" },
    { id:"n4-graph",   ch:4, diff:3, label:"Graph search",          def:"Partial outputs as paths; use future-score estimates (A*-like) to guide extension.",        href:"../chapters/chapter4/web/chapter4-study.html#sec-graph" },
    { id:"n4-bio",     ch:4, diff:2, label:"BIO tagging",           def:"Begin-Inside-Outside scheme; independent greedy predictions can violate BIO constraints.",  href:"../chapters/chapter4/web/chapter4-study.html#sec-seq" },
    { id:"n4-viterbi", ch:4, diff:3, label:"Viterbi algorithm",     def:"DP for best joint tag sequence under chain-structured scores; O(n|T|²).",                  href:"../chapters/chapter4/web/chapter4-study.html#sec-seq" },
    { id:"n4-charlm",  ch:4, diff:2, label:"Character-level model", def:"Operate on individual characters instead of words; handles OOV naturally; used in Workshop 4 surname classification.", href:"../chapters/chapter4/web/chapter4-study.html#sec-lab" },
    { id:"n4-contras", ch:4, diff:2, label:"Contrastive decoding",  def:"Penalise tokens similar to already-generated ones to reduce repetition and improve diversity.", href:"../chapters/chapter4/web/chapter4-study.html#sec-greedy" },

    // ===== CHAPTER 5: Encoder–Decoder Models =====
    { id:"n5-cbow",    ch:5, diff:1, label:"word2vec CBOW",         def:"Predict centre word from averaged context embeddings.",                                    href:"../chapters/chapter5/web/chapter5-study.html#sec-static" },
    { id:"n5-skip",    ch:5, diff:1, label:"Skip-gram",             def:"Predict context from centre word; often stronger for rare words.",                         href:"../chapters/chapter5/web/chapter5-study.html#sec-static" },
    { id:"n5-glove",   ch:5, diff:2, label:"GloVe",                 def:"Dot products approximate log co-occurrence; global statistics + learned objective.",        href:"../chapters/chapter5/web/chapter5-study.html#sec-static" },
    { id:"n5-fast",    ch:5, diff:2, label:"FastText",              def:"Word = sum of character n-gram vectors; handles rare / misspelled words.",                  href:"../chapters/chapter5/web/chapter5-study.html#sec-static" },
    { id:"n5-ctx",     ch:5, diff:2, label:"Contextual representations", def:"Per-token vectors that vary with context; bidirectional RNN; ELMo (2018).",           href:"../chapters/chapter5/web/chapter5-study.html#sec-context" },
    { id:"n5-s2s",     ch:5, diff:2, label:"Encoder–decoder (seq2seq)", def:"Encoder RNN → hidden states; decoder RNN generates target left-to-right.",             href:"../chapters/chapter5/web/chapter5-study.html#sec-encdec" },
    { id:"n5-tf",      ch:5, diff:2, label:"Teacher forcing",       def:"Feed gold previous token during training to prevent error compounding.",                   href:"../chapters/chapter5/web/chapter5-study.html#sec-train" },
    { id:"n5-bleu",    ch:5, diff:2, label:"BLEU & chrF",           def:"BLEU: word n-gram precision + brevity penalty; chrF: character n-gram F-beta.",             href:"../chapters/chapter5/web/chapter5-study.html#sec-mt" },
    { id:"n5-bpe",     ch:5, diff:2, label:"BPE tokenisation",      def:"Merge most frequent adjacent pair until vocab size K; subwords generalise to unseen words.", href:"../chapters/chapter5/web/chapter5-study.html#sec-bpe" },
    { id:"n5-bottl",   ch:5, diff:2, label:"Seq2seq bottleneck",    def:"Source compressed into one vector; sequential decoding hard to parallelise → motivates attention.", href:"../chapters/chapter5/web/chapter5-study.html#sec-attn" },
    { id:"n5-conv1d",  ch:5, diff:2, label:"CNN for text (Conv1D)", def:"1D convolutions over embedding sequences capture local n-gram patterns; pooling for classification.", href:"../chapters/chapter5/web/chapter5-study.html#sec-lab" },
    { id:"n5-finetune",ch:5, diff:2, label:"Fine-tuning",          def:"Continue training a pretrained model on task-specific data; key paradigm for ELMo → BERT era.", href:"../chapters/chapter5/web/chapter5-study.html#sec-static" },
    { id:"n5-lstm",    ch:5, diff:3, label:"BiLSTM for classification", def:"Bidirectional LSTM encodes full left+right context; pooled hidden state for sentiment etc.", href:"../chapters/chapter5/web/chapter5-study.html#sec-context" },

    // ===== CHAPTER 6: Transformer Models =====
    { id:"n6-motiv",   ch:6, diff:1, label:"Attention motivation",  def:"Weighted sum of encoder states at each step → less bottleneck, more parallelism.",          href:"../chapters/chapter6/web/chapter6-study.html#sec-motivation" },
    { id:"n6-forms",   ch:6, diff:2, label:"Attention score forms",  def:"Dot, bilinear, additive (Bahdanau), scaled dot-product (÷√d_k); key-value lookup view.",   href:"../chapters/chapter6/web/chapter6-study.html#sec-attn-forms" },
    { id:"n6-self",    ch:6, diff:2, label:"Self-attention",         def:"Each position attends to all positions in the same sequence → contextual vector.",         href:"../chapters/chapter6/web/chapter6-study.html#sec-self" },
    { id:"n6-qkv",     ch:6, diff:2, label:"Q, K, V projections",   def:"Learned W^Q, W^K, W^V transform inputs; Attention(Q,K,V) = softmax(QK^T/√d_k)V.",         href:"../chapters/chapter6/web/chapter6-study.html#sec-qkv" },
    { id:"n6-mh",      ch:6, diff:3, label:"Multi-head attention",  def:"H parallel heads in subspaces → concat → W^O; heads can specialise (syntax vs entities).", href:"../chapters/chapter6/web/chapter6-study.html#sec-qkv" },
    { id:"n6-pos",     ch:6, diff:2, label:"Positional encodings",  def:"Sinusoidal, learned, or RoPE — inject order info since self-attention is permutation-invariant.", href:"../chapters/chapter6/web/chapter6-study.html#sec-pos" },
    { id:"n6-mask",    ch:6, diff:2, label:"Causal mask",           def:"Set e_{ij}=−∞ for j>i so decoder can't attend to future tokens; preserves autoregressive property.", href:"../chapters/chapter6/web/chapter6-study.html#sec-pos" },
    { id:"n6-block",   ch:6, diff:2, label:"Transformer encoder block", def:"Self-attention + FFN sublayers, each with residual connection and layer normalisation.", href:"../chapters/chapter6/web/chapter6-study.html#sec-block" },
    { id:"n6-resln",   ch:6, diff:1, label:"Residual + LayerNorm", def:"x'=x+SubLayer(x) for gradient flow; LayerNorm normalises features per token.",               href:"../chapters/chapter6/web/chapter6-study.html#sec-block" },
    { id:"n6-cross",   ch:6, diff:3, label:"Cross-attention",       def:"Decoder queries attend to encoder keys/values — seq2seq without single bottleneck vector.", href:"../chapters/chapter6/web/chapter6-study.html#sec-decoder" },
    { id:"n6-gru",     ch:6, diff:2, label:"GRU",                  def:"Gated Recurrent Unit: update + reset gates; simpler than LSTM with fewer parameters, similar performance.", href:"../chapters/chapter6/web/chapter6-study.html#sec-lab" },
    { id:"n6-attnvis", ch:6, diff:1, label:"Attention visualisation", def:"Heatmap of attention weights showing which source positions each decoder step attends to.", href:"../chapters/chapter6/web/chapter6-study.html#sec-lab" }
  ],
  edges: [
    // Ch1 internal
    ["n1-nlp","n1-tasks",8], ["n1-tasks","n1-pipe",8], ["n1-onehot","n1-bow",9],
    ["n1-bow","n1-tfidf",8], ["n1-tfidf","n1-bm25",8], ["n1-dist","n1-svd",8],
    ["n1-dist","n1-cbow",8], ["n1-cbow","n1-skip",9], ["n1-skip","n1-window",7],
    ["n1-cosine","n1-analogy",8], ["n1-cbow","n1-bias",5],
    // Ch2 internal
    ["n2-five","n2-sent",7], ["n2-tok","n2-linear",8], ["n2-linear","n2-losses",9],
    ["n2-losses","n2-percept",8], ["n2-losses","n2-logreg",8],
    ["n2-embed","n2-linear",7], ["n2-split","n2-prf",8], ["n2-prf","n2-roc",7],
    // Ch3 internal
    ["n3-act","n3-mlp",9], ["n3-mlp","n3-sgd",7], ["n3-sgd","n3-bp",9],
    ["n3-bp","n3-reg",6], ["n3-mlp","n3-rnn",8], ["n3-rnn","n3-trenc",8],
    ["n3-rnn","n3-bptt",9], ["n3-bptt","n3-vanexp",9], ["n3-vanexp","n3-clip",8],
    // Ch4 internal
    ["n4-mod","n4-exh",7], ["n4-exh","n4-greedy",8], ["n4-greedy","n4-topkp",8],
    ["n4-greedy","n4-beam",9], ["n4-beam","n4-graph",6],
    ["n4-greedy","n4-bio",7], ["n4-bio","n4-viterbi",9],
    // Ch5 internal
    ["n5-cbow","n5-skip",9], ["n5-skip","n5-glove",7], ["n5-glove","n5-fast",6],
    ["n5-ctx","n5-s2s",8], ["n5-s2s","n5-tf",8], ["n5-s2s","n5-bleu",6],
    ["n5-s2s","n5-bpe",7], ["n5-s2s","n5-bottl",9],
    // Ch6 internal
    ["n6-motiv","n6-forms",9], ["n6-forms","n6-self",9], ["n6-self","n6-qkv",9],
    ["n6-qkv","n6-mh",9], ["n6-pos","n6-mask",8], ["n6-qkv","n6-block",8],
    ["n6-block","n6-resln",8], ["n6-block","n6-cross",9],
    // Cross-chapter links
    ["n1-pipe","n2-tok",7], ["n1-onehot","n2-tok",6], ["n1-tfidf","n2-linear",6],
    ["n1-cosine","n5-glove",6], ["n1-cbow","n5-cbow",9], ["n1-skip","n5-skip",9],
    ["n2-linear","n3-mlp",8], ["n2-logreg","n3-bp",7], ["n2-losses","n3-sgd",7],
    ["n2-prf","n5-bleu",5], ["n3-rnn","n4-greedy",7], ["n3-trenc","n4-bio",7],
    ["n3-vanexp","n5-ctx",6], ["n4-beam","n5-s2s",7], ["n4-viterbi","n4-bio",8],
    ["n5-bottl","n6-motiv",9], ["n5-ctx","n6-self",7], ["n5-bpe","n2-tok",6],
    ["n6-mh","n6-cross",8], ["n6-mask","n6-cross",8],
    // New node edges
    ["n1-dist","n1-cooccur",9], ["n1-cooccur","n1-svd",9], ["n1-bias","n1-instab",8],
    ["n2-confmat","n2-prf",9], ["n2-tok","n2-ngrams",8], ["n2-tok","n2-stopw",7],
    ["n2-tok","n2-oov",7], ["n2-oov","n5-bpe",7], ["n2-naiveB","n2-linear",7],
    ["n2-svm","n2-losses",8], ["n2-svm","n2-linear",8], ["n2-imbal","n2-prf",7],
    ["n3-vanexp","n3-lstm",9], ["n3-lstm","n3-birnn",8], ["n3-rnn","n3-birnn",7],
    ["n3-trenc","n3-pos",8], ["n3-trenc","n3-ner",8], ["n3-ner","n4-bio",8],
    ["n3-bp","n3-compg",9], ["n3-reg","n3-early",7],
    ["n4-greedy","n4-contras",7], ["n4-charlm","n3-rnn",7], ["n4-charlm","n2-oov",6],
    ["n5-conv1d","n3-mlp",6], ["n5-conv1d","n2-ngrams",6],
    ["n5-finetune","n5-ctx",8], ["n5-lstm","n3-lstm",9], ["n5-lstm","n3-birnn",9],
    ["n5-lstm","n5-ctx",8], ["n6-gru","n3-lstm",8], ["n6-gru","n3-rnn",7],
    ["n6-attnvis","n6-forms",6]
  ]
};
