window.KG_CONFIG = {
  langKey: "comp5270_lang",
  fromParam: "mkg",
  numChapters: 12,
  chapterColors: { 1:"#6c8cff", 2:"#34d399", 3:"#fbbf24", 4:"#a78bfa", 5:"#f87171", 6:"#f472b6", 7:"#38bdf8", 8:"#fb923c", 9:"#14b8a6", 10:"#e879f9", 11:"#22d3ee", 12:"#f97316" },
  chapterNames: {
    1:"Ch1 Math Foundations", 2:"Ch2 Math Foundations", 3:"Ch3 Math Foundations", 4:"Ch4 Math Foundations",
    5:"Ch5 Math Foundations", 6:"Ch6 Math Foundations", 7:"Ch7 Math Foundations", 8:"Ch8 Math Foundations",
    9:"Ch9 Math Foundations", 10:"Ch10 Math Foundations", 11:"Ch11 Math Foundations", 12:"Ch12 Math Foundations"
  },
  clickHint: { en: "Click to open Math Foundations section", zh: "点击打开数学基础页面" },
  nodes: [
    { id:"m1-sets", ch:1, diff:1, label:"Sets & Number Systems", def:"Sets, Z, Q, R, basic notation for algorithms.", href:"../chapters/chapter1/web/chapter1-math.html#sec-sets" },
    { id:"m1-notation", ch:1, diff:1, label:"Summation & Products", def:"Sigma/Pi notation and manipulating sums.", href:"../chapters/chapter1/web/chapter1-math.html#sec-notation" },
    { id:"m1-bigo", ch:1, diff:2, label:"Big-O Notation", def:"Asymptotic growth: O, Omega, Theta for runtime analysis.", href:"../chapters/chapter1/web/chapter1-math.html#sec-bigo" },
    { id:"m1-log", ch:1, diff:1, label:"Logarithms", def:"log properties, change of base, poly vs exp.", href:"../chapters/chapter1/web/chapter1-math.html#sec-log" },
    { id:"m1-prob-basics", ch:1, diff:1, label:"Probability Basics", def:"Events, axioms, discrete probability spaces.", href:"../chapters/chapter1/web/chapter1-math.html#sec-prob-basics" },
    { id:"m1-rv", ch:1, diff:1, label:"Random Variables", def:"Discrete RVs, PMF, CDF.", href:"../chapters/chapter1/web/chapter1-math.html#sec-rv" },
    { id:"m1-expectation", ch:1, diff:1, label:"Expectation", def:"E[X] definition and basic properties.", href:"../chapters/chapter1/web/chapter1-math.html#sec-expectation" },
    { id:"m1-linearity", ch:1, diff:2, label:"Linearity of Expectation", def:"E[sum]=sum E even without independence.", href:"../chapters/chapter1/web/chapter1-math.html#sec-linearity" },
    { id:"m1-variance", ch:1, diff:2, label:"Variance", def:"Var(X), standard deviation, Var of sums.", href:"../chapters/chapter1/web/chapter1-math.html#sec-variance" },
    { id:"m1-indicator", ch:1, diff:2, label:"Indicator Variables", def:"0/1 variables; counting via expectation.", href:"../chapters/chapter1/web/chapter1-math.html#sec-indicator" },
    { id:"m1-independence", ch:1, diff:2, label:"Independence", def:"Independent RVs and product of expectations.", href:"../chapters/chapter1/web/chapter1-math.html#sec-independence" },
    { id:"m1-bernoulli", ch:1, diff:2, label:"Bernoulli & Binomial", def:"Bernoulli trials, binomial distribution.", href:"../chapters/chapter1/web/chapter1-math.html#sec-bernoulli" },
    { id:"m1-geometric", ch:1, diff:2, label:"Geometric Distribution", def:"Waiting time until first success.", href:"../chapters/chapter1/web/chapter1-math.html#sec-geometric" },
    { id:"m1-tailsum", ch:1, diff:2, label:"Tail-Sum Formula", def:"E[X] from tail probabilities for nonnegative integer X.", href:"../chapters/chapter1/web/chapter1-math.html#sec-tailsum" },
    { id:"m1-harmonic", ch:1, diff:2, label:"Harmonic Numbers", def:"H_n ~ ln n; appears in many analyses.", href:"../chapters/chapter1/web/chapter1-math.html#sec-harmonic" },
    { id:"m1-jensen", ch:1, diff:3, label:"Jensen's Inequality", def:"Convex functions and E[f(X)] vs f(E[X]).", href:"../chapters/chapter1/web/chapter1-math.html#sec-jensen" },
    { id:"m1-permutations", ch:1, diff:2, label:"Permutations & Fixed Points", def:"Counting permutations, derangements.", href:"../chapters/chapter1/web/chapter1-math.html#sec-permutations" },
    { id:"m1-recurrence", ch:1, diff:3, label:"Recurrences & ODE analogies", def:"Solving recurrences arising in algorithms.", href:"../chapters/chapter1/web/chapter1-math.html#sec-recurrence" },
    { id:"m1-prob-toolkit", ch:1, diff:1, label:"Probability toolkit (study)", def:"Tail-sum, Var, Bernoulli/Binomial, Jensen — consolidated reference.", href:"../chapters/chapter1/web/chapter1-study.html#sec-prob-facts" },
    { id:"m1-card-deck", ch:1, diff:1, label:"Card deck expectation", def:"Linearity without independence: 12 expected same-suit adjacencies.", href:"../chapters/chapter1/web/chapter1-study.html#sec-card-experiment" },
    { id:"m2-mgf", ch:2, diff:3, label:"Moment-Generating Functions", def:"M_X(t)=E[e^{tX}]; Chernoff proofs.", href:"../chapters/chapter2/web/chapter2-math.html#sec-mgf" },
    { id:"m2-why-conc", ch:2, diff:1, label:"Why concentration?", def:"Motivation: expectations need tail bounds for algorithm guarantees.", href:"../chapters/chapter2/web/chapter2-study.html#sec-why-concentration" },
    { id:"m2-exp-log", ch:2, diff:2, label:"Exp & Log Properties", def:"Inequalities used in tail bounds.", href:"../chapters/chapter2/web/chapter2-math.html#sec-exp-properties" },
    { id:"m2-series", ch:2, diff:2, label:"Series & Convergence", def:"Tools for bounding sums in proofs.", href:"../chapters/chapter2/web/chapter2-math.html#sec-series" },
    { id:"m2-poisson", ch:2, diff:2, label:"Poisson (Ch2 math)", def:"Poisson distribution and tails.", href:"../chapters/chapter2/web/chapter2-math.html#sec-poisson" },
    { id:"m2-geom", ch:2, diff:2, label:"Geometric (Ch2 math)", def:"Geometric sums and expectations.", href:"../chapters/chapter2/web/chapter2-math.html#sec-geometric" },
    { id:"m2-markov", ch:2, diff:2, label:"Markov Inequality (deep)", def:"Proof and applications.", href:"../chapters/chapter2/web/chapter2-math.html#sec-markov-deep" },
    { id:"m2-cheb", ch:2, diff:2, label:"Chebyshev (deep)", def:"Variance-based tails.", href:"../chapters/chapter2/web/chapter2-math.html#sec-chebyshev-deep" },
    { id:"m2-chernoff", ch:2, diff:4, label:"Chernoff proof", def:"Full Chernoff bound derivation.", href:"../chapters/chapter2/web/chapter2-math.html#sec-chernoff-proof" },
    { id:"m2-hoeff", ch:2, diff:3, label:"Hoeffding details", def:"Bounded differences viewpoint.", href:"../chapters/chapter2/web/chapter2-math.html#sec-hoeffding-detail" },
    { id:"m2-calculus", ch:2, diff:3, label:"Calculus in proofs", def:"Optimizing bounds over t.", href:"../chapters/chapter2/web/chapter2-math.html#sec-optimization" },
    { id:"m2-key-analytic", ch:2, diff:4, label:"Key analytic inequalities", def:"AM-GM, Cauchy, etc. for proofs.", href:"../chapters/chapter2/web/chapter2-math.html#sec-key-inequalities" },
    { id:"m3-counting", ch:3, diff:2, label:"Counting & Combinatorics", def:"Permutations, combinations, stars-and-bars.", href:"../chapters/chapter3/web/chapter3-math.html#sec-counting" },
    { id:"m3-balls-bins", ch:3, diff:1, label:"Balls-in-bins (study)", def:"Unified model for collisions, coverage, max load.", href:"../chapters/chapter3/web/chapter3-study.html#sec-intro" },
    { id:"m3-stirling", ch:3, diff:3, label:"Stirling's Approximation", def:"n! asymptotics.", href:"../chapters/chapter3/web/chapter3-math.html#sec-stirling" },
    { id:"m3-harmonic", ch:3, diff:2, label:"Harmonic Numbers (Ch3)", def:"H_n in coupon collector and loads.", href:"../chapters/chapter3/web/chapter3-math.html#sec-harmonic" },
    { id:"m3-geom", ch:3, diff:2, label:"Geometric (Ch3)", def:"Geometric waiting in phases.", href:"../chapters/chapter3/web/chapter3-math.html#sec-geometric" },
    { id:"m3-indicators", ch:3, diff:2, label:"Indicators & Variance", def:"Decomposing counts; Var of sums.", href:"../chapters/chapter3/web/chapter3-math.html#sec-indicators" },
    { id:"m3-moment", ch:3, diff:3, label:"Moment methods", def:"Using moments for bounds.", href:"../chapters/chapter3/web/chapter3-math.html#sec-moment" },
    { id:"m3-poisson", ch:3, diff:3, label:"Poisson approximation", def:"Binomial ~ Poisson regime.", href:"../chapters/chapter3/web/chapter3-math.html#sec-poisson" },
    { id:"m3-jensen", ch:3, diff:3, label:"Jensen & MGF trick", def:"Convexity in probabilistic proofs.", href:"../chapters/chapter3/web/chapter3-math.html#sec-jensen" },
    { id:"m4-graphs", ch:4, diff:2, label:"Graph theory basics", def:"Vertices, edges, cuts.", href:"../chapters/chapter4/web/chapter4-math.html#sec-graphs" },
    { id:"m4-rand", ch:4, diff:3, label:"Randomness complexity", def:"bits, random vs deterministic.", href:"../chapters/chapter4/web/chapter4-math.html#sec-randomness" },
    { id:"m4-pairwise", ch:4, diff:4, label:"Pairwise independence", def:"Limited randomness constructions.", href:"../chapters/chapter4/web/chapter4-math.html#sec-pairwise-math" },
    { id:"m4-hash", ch:4, diff:3, label:"Hash families", def:"Universal hashing math.", href:"../chapters/chapter4/web/chapter4-math.html#sec-hash" },
    { id:"m4-condexp", ch:4, diff:4, label:"Conditional expectation", def:"Tower property; derandomization.", href:"../chapters/chapter4/web/chapter4-math.html#sec-cond-exp" },
    { id:"m4-probmethod", ch:4, diff:4, label:"Probabilistic method", def:"Existence via positive probability.", href:"../chapters/chapter4/web/chapter4-math.html#sec-prob-method-math" },
    { id:"m4-approx", ch:4, diff:3, label:"Approximation algorithms", def:"Randomized rounding setup.", href:"../chapters/chapter4/web/chapter4-math.html#sec-approx" },
    { id:"m5-graph-review", ch:5, diff:2, label:"Graph theory review", def:"Cuts, contractions.", href:"../chapters/chapter5/web/chapter5-math.html#sec-graph-review" },
    { id:"m5-contract", ch:5, diff:3, label:"Edge contraction", def:"Graph minors under contraction.", href:"../chapters/chapter5/web/chapter5-math.html#sec-contraction" },
    { id:"m5-cond-prod", ch:5, diff:3, label:"Conditional probability products", def:"Analyzing sequential random choices.", href:"../chapters/chapter5/web/chapter5-math.html#sec-conditional-prob" },
    { id:"m5-recur", ch:5, diff:3, label:"Recurrence relations", def:"Recurrences in graph algorithms.", href:"../chapters/chapter5/web/chapter5-math.html#sec-recurrences" },
    { id:"m5-mst", ch:5, diff:3, label:"MST properties", def:"Cuts, cycles, Boruvka/Kruskal foundations.", href:"../chapters/chapter5/web/chapter5-math.html#sec-mst-props" },
    { id:"m5-counting", ch:5, diff:3, label:"Counting arguments", def:"Min-cut enumeration ideas.", href:"../chapters/chapter5/web/chapter5-math.html#sec-counting-math" },
    { id:"m6-dictionary", ch:6, diff:1, label:"Dictionary ADT", def:"Insert/Lookup/Remove; hash tables vs BST trade-offs.", href:"../chapters/chapter6/web/chapter6-study.html#sec-dictionary" },
    { id:"m6-mod", ch:6, diff:3, label:"Modular arithmetic & fields", def:"Z_p for hashing.", href:"../chapters/chapter6/web/chapter6-math.html#sec-modular" },
    { id:"m6-pigeon", ch:6, diff:2, label:"Pigeonhole principle", def:"Existence proofs.", href:"../chapters/chapter6/web/chapter6-math.html#sec-pigeonhole" },
    { id:"m6-hash-construct", ch:6, diff:3, label:"Hash constructions", def:"Polynomial hashing over fields.", href:"../chapters/chapter6/web/chapter6-math.html#sec-hash-construct" },
    { id:"m6-collisions", ch:6, diff:2, label:"Expected collisions", def:"Birthday-style analysis.", href:"../chapters/chapter6/web/chapter6-math.html#sec-collisions" },
    { id:"m6-load", ch:6, diff:3, label:"Load & birthday", def:"Load factor vs collision prob.", href:"../chapters/chapter6/web/chapter6-math.html#sec-load-birthday" },
    { id:"m6-bloom", ch:6, diff:3, label:"Bloom filter analysis", def:"False positive probability.", href:"../chapters/chapter6/web/chapter6-math.html#sec-bloom-prob" },
    { id:"m7-metric", ch:7, diff:2, label:"Metric spaces", def:"Distance axioms; NN problem.", href:"../chapters/chapter7/web/chapter7-math.html#sec-metric-spaces" },
    { id:"m7-norms", ch:7, diff:3, label:"Inner products & norms", def:"l2, Cauchy-Schwarz.", href:"../chapters/chapter7/web/chapter7-math.html#sec-norms" },
    { id:"m7-gauss", ch:7, diff:3, label:"Gaussian vectors", def:"Spherical symmetry and projections.", href:"../chapters/chapter7/web/chapter7-math.html#sec-gaussians" },
    { id:"m7-matrix", ch:7, diff:3, label:"Matrix-vector as projection", def:"JL lemma linear algebra.", href:"../chapters/chapter7/web/chapter7-math.html#sec-matrix" },
    { id:"m7-chi", ch:7, diff:4, label:"Chi-squared concentration", def:"Norms of Gaussian vectors.", href:"../chapters/chapter7/web/chapter7-math.html#sec-chi-squared" },
    { id:"m7-union", ch:7, diff:3, label:"Logs & union bound", def:"High-dimension failure events.", href:"../chapters/chapter7/web/chapter7-math.html#sec-union-bound" },
    { id:"m8-log", ch:8, diff:1, label:"Logarithms review", def:"log in space bounds.", href:"../chapters/chapter8/web/chapter8-math.html#sec-logarithms" },
    { id:"m8-geom", ch:8, diff:2, label:"Geometric RVs", def:"Morris-style analysis.", href:"../chapters/chapter8/web/chapter8-math.html#sec-geometric" },
    { id:"m8-total-exp", ch:8, diff:3, label:"Law of total expectation", def:"Conditioning on phases.", href:"../chapters/chapter8/web/chapter8-math.html#sec-total-expectation" },
    { id:"m8-cond-var", ch:8, diff:4, label:"Conditional variance", def:"Eve's law.", href:"../chapters/chapter8/web/chapter8-math.html#sec-conditional-variance" },
    { id:"m8-zeros", ch:8, diff:3, label:"Trailing zeros", def:"Divisors and counting.", href:"../chapters/chapter8/web/chapter8-math.html#sec-trailing-zeros" },
    { id:"m8-mom", ch:8, diff:4, label:"Median-of-means", def:"Variance reduction via subsamples.", href:"../chapters/chapter8/web/chapter8-math.html#sec-median-of-means" },
    { id:"m9-univ-hash", ch:9, diff:3, label:"Strongly universal hashing", def:"4-universal families for sketches.", href:"../chapters/chapter9/web/chapter9-math.html#sec-universal-hash" },
    { id:"m9-sign", ch:9, diff:3, label:"Sign hash functions", def:"Sketching inner products.", href:"../chapters/chapter9/web/chapter9-math.html#sec-sign-hash" },
    { id:"m9-lp", ch:9, diff:3, label:"l_p norms", def:"Error metrics for sketches.", href:"../chapters/chapter9/web/chapter9-math.html#sec-lp-norms" },
    { id:"m9-var-sketch", ch:9, diff:3, label:"Variance of sketch estimators", def:"CS vs CMS analysis.", href:"../chapters/chapter9/web/chapter9-math.html#sec-variance-sketch" },
    { id:"m9-mc", ch:9, diff:2, label:"Markov & Chebyshev", def:"Tail tools for sketches.", href:"../chapters/chapter9/web/chapter9-math.html#sec-markov-chebyshev" },
    { id:"m9-med", ch:9, diff:3, label:"Median & min amplification", def:"Boosting estimator success.", href:"../chapters/chapter9/web/chapter9-math.html#sec-median-amplification" },
    { id:"m9-compare", ch:9, diff:3, label:"MG vs CS vs CMS", def:"Space, model (cash register vs turnstile), and norm trade-offs.", href:"../chapters/chapter9/web/chapter9-study.html#sec-comparison" },
    { id:"m9-cs-cms-ui", ch:9, diff:2, label:"CS vs CMS interactive", def:"Median vs min aggregation on same stream.", href:"../chapters/chapter9/web/chapter9-study.html#sec-cs-vs-cms" },
    { id:"m9-cms-sim", ch:9, diff:1, label:"CMS simulator", def:"Observe collisions inflating estimates.", href:"../chapters/chapter9/web/chapter9-study.html#sec-simulator" },
    { id:"m10-amgm", ch:10, diff:2, label:"AM-GM inequality", def:"LP relaxations and rounding.", href:"../chapters/chapter10/web/chapter10-math.html#sec-amgm" },
    { id:"m10-concavity", ch:10, diff:3, label:"Concavity & Jensen", def:"Randomized rounding analysis.", href:"../chapters/chapter10/web/chapter10-math.html#sec-concavity" },
    { id:"m10-approx", ch:10, diff:3, label:"Approximation ratios", def:"alpha-approximation definitions.", href:"../chapters/chapter10/web/chapter10-math.html#sec-approx" },
    { id:"m10-1e", ch:10, diff:3, label:"The 1-1/e limit", def:"Submodular / coverage limits.", href:"../chapters/chapter10/web/chapter10-math.html#sec-1e" },
    { id:"m10-bestof2", ch:10, diff:3, label:"Best-of-two & 3/4", def:"max(LP rounding, random) gives a 3/4 Max-SAT approximation.", href:"../chapters/chapter10/web/chapter10-study.html#sec-bestof2" },
    { id:"m11-framework", ch:11, diff:2, label:"Learning vs testing setup", def:"Sample model; estimation vs hypothesis testing tasks.", href:"../chapters/chapter11/web/chapter11-study.html#sec-setup" },
    { id:"m11-scheffe", ch:11, diff:3, label:"Scheffe set (TV)", def:"Attaining set for TV; links to optimal tests.", href:"../chapters/chapter11/web/chapter11-study.html#sec-tv-distance" },
    { id:"m11-pearson", ch:11, diff:3, label:"Pearson-Neyman (study)", def:"Type-I/II vs TV; likelihood-ratio tests.", href:"../chapters/chapter11/web/chapter11-study.html#sec-pearson-neyman" },
    { id:"m11-lp", ch:11, diff:3, label:"l_p norms review", def:"Distances between distributions.", href:"../chapters/chapter11/web/chapter11-math.html#sec-lp-norms" },
    { id:"m11-tv", ch:11, diff:3, label:"Total variation formal", def:"TV distance properties.", href:"../chapters/chapter11/web/chapter11-math.html#sec-tv-formal" },
    { id:"m11-dpi", ch:11, diff:4, label:"Data processing (TV)", def:"Post-processing contracts TV; fails for l2/l_inf.", href:"../chapters/chapter11/web/chapter11-study.html#sec-dpi" },
    { id:"m11-chi", ch:11, diff:4, label:"Chi-squared divergence", def:"Hypothesis testing.", href:"../chapters/chapter11/web/chapter11-math.html#sec-chi-squared" },
    { id:"m11-hoeff", ch:11, diff:3, label:"Hoeffding (Ch11)", def:"Sample complexity bounds.", href:"../chapters/chapter11/web/chapter11-math.html#sec-hoeffding" },
    { id:"m11-coin", ch:11, diff:2, label:"Bernoulli learning", def:"Estimating bias with O(1/eps^2 log 1/delta) samples.", href:"../chapters/chapter11/web/chapter11-study.html#sec-learning-coin" },
    { id:"m11-optimal", ch:11, diff:4, label:"Testing vs learning rates", def:"sqrt(k)/eps^2 vs k/eps^2 sample complexity gap.", href:"../chapters/chapter11/web/chapter11-study.html#sec-optimal" },
    { id:"m11-bday", ch:11, diff:2, label:"Birthday paradox", def:"Collision events in testing.", href:"../chapters/chapter11/web/chapter11-math.html#sec-birthday" },
    { id:"m11-multi", ch:11, diff:3, label:"Multinomial distribution", def:"Counts of categorical data.", href:"../chapters/chapter11/web/chapter11-math.html#sec-multinomial" },
    { id:"m12-potential", ch:12, diff:3, label:"Potential functions", def:"MWU potential proofs.", href:"../chapters/chapter12/web/chapter12-math.html#sec-potential" },
    { id:"m12-logbd", ch:12, diff:3, label:"Logarithmic bounds", def:"ln n terms in regret.", href:"../chapters/chapter12/web/chapter12-math.html#sec-logarithmic" },
    { id:"m12-decay", ch:12, diff:3, label:"Geometric weight decay", def:"Multiplicative updates.", href:"../chapters/chapter12/web/chapter12-math.html#sec-geometric-decay" },
    { id:"m12-beta", ch:12, diff:3, label:"beta trade-off", def:"Tuning MWU parameter.", href:"../chapters/chapter12/web/chapter12-math.html#sec-beta-tradeoff" },
    { id:"m12-telescoping", ch:12, diff:3, label:"Telescoping & ln inequality", def:"Summing regret bounds.", href:"../chapters/chapter12/web/chapter12-math.html#sec-telescoping" },
    { id:"m12-consistent", ch:12, diff:3, label:"Consistent expert elimination", def:"Potential |S| drops when an always-correct expert exists.", href:"../chapters/chapter12/web/chapter12-study.html#sec-consistent" },
    { id:"m12-mwu-beta-study", ch:12, diff:3, label:"MWU(beta) bound (study)", def:"General beta penalty and trade-offs.", href:"../chapters/chapter12/web/chapter12-study.html#sec-mwu-beta" },
    { id:"m12-det-rand", ch:12, diff:3, label:"Deterministic vs randomised", def:"Factor-2 gap facts.", href:"../chapters/chapter12/web/chapter12-math.html#sec-det-vs-rand" }
  ],
  edges: [
    ["m1-sets","m1-notation",8],
    ["m1-notation","m1-bigo",8],
    ["m1-bigo","m1-log",8],
    ["m1-log","m1-prob-basics",8],
    ["m1-prob-basics","m1-rv",8],
    ["m1-rv","m1-expectation",8],
    ["m1-expectation","m1-linearity",8],
    ["m1-linearity","m1-variance",8],
    ["m1-variance","m1-indicator",8],
    ["m1-indicator","m1-independence",8],
    ["m1-independence","m1-bernoulli",8],
    ["m1-bernoulli","m1-geometric",8],
    ["m1-geometric","m1-tailsum",8],
    ["m1-tailsum","m1-harmonic",8],
    ["m1-harmonic","m1-jensen",8],
    ["m1-jensen","m1-permutations",8],
    ["m1-permutations","m1-recurrence",8],
    ["m2-mgf","m2-exp-log",8],
    ["m2-exp-log","m2-series",8],
    ["m2-series","m2-poisson",8],
    ["m2-poisson","m2-geom",8],
    ["m2-geom","m2-markov",8],
    ["m2-markov","m2-cheb",8],
    ["m2-cheb","m2-chernoff",8],
    ["m2-chernoff","m2-hoeff",8],
    ["m2-hoeff","m2-calculus",8],
    ["m2-calculus","m2-key-analytic",8],
    ["m3-counting","m3-stirling",8],
    ["m3-stirling","m3-harmonic",8],
    ["m3-harmonic","m3-geom",8],
    ["m3-geom","m3-indicators",8],
    ["m3-indicators","m3-moment",8],
    ["m3-moment","m3-poisson",8],
    ["m3-poisson","m3-jensen",8],
    ["m4-graphs","m4-rand",8],
    ["m4-rand","m4-pairwise",8],
    ["m4-pairwise","m4-hash",8],
    ["m4-hash","m4-condexp",8],
    ["m4-condexp","m4-probmethod",8],
    ["m4-probmethod","m4-approx",8],
    ["m5-graph-review","m5-contract",8],
    ["m5-contract","m5-cond-prod",8],
    ["m5-cond-prod","m5-recur",8],
    ["m5-recur","m5-mst",8],
    ["m5-mst","m5-counting",8],
    ["m6-mod","m6-pigeon",8],
    ["m6-pigeon","m6-hash-construct",8],
    ["m6-hash-construct","m6-collisions",8],
    ["m6-collisions","m6-load",8],
    ["m6-load","m6-bloom",8],
    ["m7-metric","m7-norms",8],
    ["m7-norms","m7-gauss",8],
    ["m7-gauss","m7-matrix",8],
    ["m7-matrix","m7-chi",8],
    ["m7-chi","m7-union",8],
    ["m8-log","m8-geom",8],
    ["m8-geom","m8-total-exp",8],
    ["m8-total-exp","m8-cond-var",8],
    ["m8-cond-var","m8-zeros",8],
    ["m8-zeros","m8-mom",8],
    ["m9-univ-hash","m9-sign",8],
    ["m9-sign","m9-lp",8],
    ["m9-lp","m9-var-sketch",8],
    ["m9-var-sketch","m9-mc",8],
    ["m9-mc","m9-med",8],
    ["m9-med","m9-compare",9],
    ["m9-compare","m9-cs-cms-ui",8],
    ["m9-med","m9-cms-sim",7],
    ["m10-amgm","m10-concavity",8],
    ["m10-concavity","m10-approx",8],
    ["m10-approx","m10-1e",8],
    ["m10-approx","m10-bestof2",9],
    ["m10-bestof2","m10-1e",7],
    ["m11-framework","m11-lp",8],
    ["m11-lp","m11-tv",8],
    ["m11-tv","m11-scheffe",9],
    ["m11-scheffe","m11-dpi",8],
    ["m11-dpi","m11-chi",8],
    ["m11-tv","m11-pearson",8],
    ["m11-pearson","m11-hoeff",7],
    ["m11-chi","m11-hoeff",8],
    ["m11-hoeff","m11-coin",8],
    ["m11-coin","m11-optimal",8],
    ["m11-optimal","m11-bday",8],
    ["m11-bday","m11-multi",8],
    ["m12-potential","m12-mwu-beta-study",7],
    ["m12-mwu-beta-study","m12-beta",8],
    ["m12-potential","m12-logbd",8],
    ["m12-logbd","m12-decay",8],
    ["m12-decay","m12-beta",8],
    ["m12-beta","m12-telescoping",8],
    ["m12-telescoping","m12-det-rand",8],
    ["m12-potential","m12-consistent",8],
    ["m12-consistent","m12-det-rand",7],
    ["m1-linearity","m3-indicators",7],
    ["m1-harmonic","m3-harmonic",8],
    ["m1-jensen","m3-jensen",7],
    ["m1-geometric","m3-geom",7],
    ["m1-linearity","m1-prob-toolkit",8],
    ["m1-indicator","m1-card-deck",8],
    ["m1-tailsum","m1-prob-toolkit",8],
    ["m2-why-conc","m2-markov",8],
    ["m3-counting","m3-balls-bins",8],
    ["m6-pigeon","m6-dictionary",8],
    ["m1-expectation","m2-markov",7],
    ["m1-variance","m2-cheb",7],
    ["m2-mgf","m2-chernoff",9],
    ["m2-key-analytic","m10-amgm",6],
    ["m4-hash","m6-hash-construct",7],
    ["m1-prob-basics","m4-condexp",6],
    ["m6-collisions","m11-bday",6],
    ["m7-norms","m9-lp",8],
    ["m7-norms","m11-lp",8],
    ["m2-hoeff","m11-hoeff",7],
    ["m7-chi","m11-chi",7],
    ["m8-mom","m2-cheb",6],
    ["m9-mc","m2-markov",7],
    ["m10-concavity","m1-jensen",8],
    ["m1-recurrence","m5-recur",6],
    ["m3-counting","m5-counting",6],
    ["m4-graphs","m5-graph-review",8],
    ["m8-total-exp","m4-condexp",7],
    ["m12-potential","m12-decay",8]
  ]
};
